version: '3.1'
services:
  web:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    depends_on:
      - mongodb
    build: backend
    ports:
      - "5000:5000"
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
